Dialog#main
{
    title:"${settings}"
    icon:"icons/24/setting.svg" 
    w:850
    h:600
    layout:VBoxLayout
    Splitter
    {
        type:horizontal
        sizes:"100,500"
        List#settings_list
        {
            item-height:34
            icon-size:24
            min-width:120
            css:"background:transparent"
            selected:0

            {
                text:"${general}"
                icon:"icons/24/setting.svg"
                data:"general"
            }
            {
                text:"${network}"
                icon:"icons/24/internet.svg"
                data:"network"
            }
            {
                text:"${service}"
                icon:"icons/24/service.svg"
                data:"service"
            }
            {
                text:"${leeches}"
                icon:"icons/24/leech.svg"
                data:"leeches"
            }
            {
                text:"${file_browser}"
                icon:"icons/24/directory.svg"
                data:"nfs"
            }
            {
                text:"HTTP"
                icon:"icons/24/web.svg"
                data:"http"
            }
            {
                text:"FTP"
                icon:"icons/24/ftp.svg"
                data:"ftp"
            }
            {
                text:"SSH"
                icon:"icons/24/ssh.svg"
                data:"ssh"
            }
            {
                text:"Torrent"
                icon:"icons/24/torrent.svg"
                data:"torrent"
            }
            {
                text:"ED2K"
                icon:"icons/24/emule.svg"
                data:"ed2k"
            }
            {
                text:"Stream"
                icon:"icons/24/stream.svg"
                data:"stream"
            }
        }
        Widgets#settings_widgets
        {
           
        }
        
    }
    HBoxLayout
    {
        <==>
        Button#settings_save{
            text:"${save}"
            icon:"icons/16/save.svg"
        }
        Button#settings_cancel{
            text:"${cancel}"
            click:$close{#main}()
        }
    }
    
}
